# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 742)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 811, 721))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 0, 381, 451))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_6)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 365, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 9, 0, 1, 1)
        self.dcc_sp_s1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.dcc_sp_s1.setMaximum(99999.99)
        self.dcc_sp_s1.setProperty("value", 1000.0)
        self.dcc_sp_s1.setObjectName("dcc_sp_s1")
        self.gridLayout.addWidget(self.dcc_sp_s1, 6, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.start_pb_s1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.start_pb_s1.setObjectName("start_pb_s1")
        self.gridLayout.addWidget(self.start_pb_s1, 3, 1, 1, 1)
        self.dist_sp_s1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.dist_sp_s1.setMaximum(99999.99)
        self.dist_sp_s1.setObjectName("dist_sp_s1")
        self.gridLayout.addWidget(self.dist_sp_s1, 9, 1, 1, 1)
        self.acc_sp_s1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.acc_sp_s1.setMaximum(99999.99)
        self.acc_sp_s1.setProperty("value", 1000.0)
        self.acc_sp_s1.setObjectName("acc_sp_s1")
        self.gridLayout.addWidget(self.acc_sp_s1, 5, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 10, 0, 1, 1)
        self.vel_le_s1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.vel_le_s1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vel_le_s1.sizePolicy().hasHeightForWidth())
        self.vel_le_s1.setSizePolicy(sizePolicy)
        self.vel_le_s1.setMaxLength(16)
        self.vel_le_s1.setObjectName("vel_le_s1")
        self.gridLayout.addWidget(self.vel_le_s1, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.modeSelection_cb_s1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.modeSelection_cb_s1.setObjectName("modeSelection_cb_s1")
        self.modeSelection_cb_s1.addItem("")
        self.modeSelection_cb_s1.addItem("")
        self.modeSelection_cb_s1.addItem("")
        self.modeSelection_cb_s1.addItem("")
        self.modeSelection_cb_s1.addItem("")
        self.modeSelection_cb_s1.addItem("")
        self.gridLayout.addWidget(self.modeSelection_cb_s1, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.servoOn_pb_s1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 36, 101))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 240, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.servoOn_pb_s1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.servoOn_pb_s1.setFont(font)
        self.servoOn_pb_s1.setCheckable(False)
        self.servoOn_pb_s1.setChecked(False)
        self.servoOn_pb_s1.setObjectName("servoOn_pb_s1")
        self.gridLayout.addWidget(self.servoOn_pb_s1, 2, 1, 1, 1)
        self.vel_sp_s1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.vel_sp_s1.setFont(font)
        self.vel_sp_s1.setMinimum(-10000.0)
        self.vel_sp_s1.setMaximum(99999.99)
        self.vel_sp_s1.setProperty("value", 5000.0)
        self.vel_sp_s1.setObjectName("vel_sp_s1")
        self.gridLayout.addWidget(self.vel_sp_s1, 4, 1, 1, 1)
        self.direction_sb_s1 = QtWidgets.QScrollBar(self.gridLayoutWidget)
        self.direction_sb_s1.setMaximum(1)
        self.direction_sb_s1.setPageStep(1)
        self.direction_sb_s1.setOrientation(QtCore.Qt.Horizontal)
        self.direction_sb_s1.setObjectName("direction_sb_s1")
        self.gridLayout.addWidget(self.direction_sb_s1, 7, 1, 1, 1)
        self.dcc_le_s1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.dcc_le_s1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dcc_le_s1.sizePolicy().hasHeightForWidth())
        self.dcc_le_s1.setSizePolicy(sizePolicy)
        self.dcc_le_s1.setMaxLength(16)
        self.dcc_le_s1.setObjectName("dcc_le_s1")
        self.gridLayout.addWidget(self.dcc_le_s1, 6, 2, 1, 1)
        self.pos_le_s1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.pos_le_s1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_le_s1.sizePolicy().hasHeightForWidth())
        self.pos_le_s1.setSizePolicy(sizePolicy)
        self.pos_le_s1.setMaxLength(16)
        self.pos_le_s1.setObjectName("pos_le_s1")
        self.gridLayout.addWidget(self.pos_le_s1, 8, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 8, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.mcerror_cb_s1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.mcerror_cb_s1.setEnabled(False)
        self.mcerror_cb_s1.setObjectName("mcerror_cb_s1")
        self.mcerror_cb_s1.addItem("")
        self.mcerror_cb_s1.addItem("")
        self.mcerror_cb_s1.addItem("")
        self.mcerror_cb_s1.addItem("")
        self.mcerror_cb_s1.addItem("")
        self.mcerror_cb_s1.addItem("")
        self.mcerror_cb_s1.addItem("")
        self.mcerror_cb_s1.addItem("")
        self.gridLayout.addWidget(self.mcerror_cb_s1, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.pos_sp_s1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.pos_sp_s1.setMinimum(-360.0)
        self.pos_sp_s1.setMaximum(360.0)
        self.pos_sp_s1.setObjectName("pos_sp_s1")
        self.gridLayout.addWidget(self.pos_sp_s1, 8, 1, 1, 1)
        self.errID_lb_s1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.errID_lb_s1.setAutoFillBackground(True)
        self.errID_lb_s1.setFrameShape(QtWidgets.QFrame.Box)
        self.errID_lb_s1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.errID_lb_s1.setLineWidth(2)
        self.errID_lb_s1.setIndent(-1)
        self.errID_lb_s1.setObjectName("errID_lb_s1")
        self.gridLayout.addWidget(self.errID_lb_s1, 10, 2, 1, 1)
        self.dir_lb_s1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dir_lb_s1.setObjectName("dir_lb_s1")
        self.gridLayout.addWidget(self.dir_lb_s1, 7, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.acc_le_s1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.acc_le_s1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acc_le_s1.sizePolicy().hasHeightForWidth())
        self.acc_le_s1.setSizePolicy(sizePolicy)
        self.acc_le_s1.setMaxLength(16)
        self.acc_le_s1.setObjectName("acc_le_s1")
        self.gridLayout.addWidget(self.acc_le_s1, 5, 2, 1, 1)
        self.reset_pb_s1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.reset_pb_s1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_pb_s1.sizePolicy().hasHeightForWidth())
        self.reset_pb_s1.setSizePolicy(sizePolicy)
        self.reset_pb_s1.setMinimumSize(QtCore.QSize(0, 10))
        self.reset_pb_s1.setMaximumSize(QtCore.QSize(200, 200))
        self.reset_pb_s1.setAutoFillBackground(True)
        self.reset_pb_s1.setObjectName("reset_pb_s1")
        self.gridLayout.addWidget(self.reset_pb_s1, 11, 1, 1, 1)
        self.driver_error_lb_s1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.driver_error_lb_s1.setAutoFillBackground(True)
        self.driver_error_lb_s1.setFrameShape(QtWidgets.QFrame.Box)
        self.driver_error_lb_s1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.driver_error_lb_s1.setLineWidth(2)
        self.driver_error_lb_s1.setIndent(-1)
        self.driver_error_lb_s1.setObjectName("driver_error_lb_s1")
        self.gridLayout.addWidget(self.driver_error_lb_s1, 11, 2, 1, 1)
        self.statusword_lb_s1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.statusword_lb_s1.setObjectName("statusword_lb_s1")
        self.gridLayout.addWidget(self.statusword_lb_s1, 3, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(390, 0, 380, 311))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 171, 227))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sw_0_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.sw_0_rb_s1.setEnabled(False)
        self.sw_0_rb_s1.setAutoExclusive(False)
        self.sw_0_rb_s1.setObjectName("sw_0_rb_s1")
        self.verticalLayout.addWidget(self.sw_0_rb_s1)
        self.sw_1_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.sw_1_rb_s1.setEnabled(False)
        self.sw_1_rb_s1.setAutoExclusive(False)
        self.sw_1_rb_s1.setObjectName("sw_1_rb_s1")
        self.verticalLayout.addWidget(self.sw_1_rb_s1)
        self.sw_2_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.sw_2_rb_s1.setEnabled(False)
        self.sw_2_rb_s1.setAutoExclusive(False)
        self.sw_2_rb_s1.setObjectName("sw_2_rb_s1")
        self.verticalLayout.addWidget(self.sw_2_rb_s1)
        self.sw_3_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.sw_3_rb_s1.setEnabled(False)
        self.sw_3_rb_s1.setAutoExclusive(False)
        self.sw_3_rb_s1.setObjectName("sw_3_rb_s1")
        self.verticalLayout.addWidget(self.sw_3_rb_s1)
        self.sw_4_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.sw_4_rb_s1.setEnabled(False)
        self.sw_4_rb_s1.setAutoExclusive(False)
        self.sw_4_rb_s1.setObjectName("sw_4_rb_s1")
        self.verticalLayout.addWidget(self.sw_4_rb_s1)
        self.sw_5_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.sw_5_rb_s1.setEnabled(False)
        self.sw_5_rb_s1.setAutoExclusive(False)
        self.sw_5_rb_s1.setObjectName("sw_5_rb_s1")
        self.verticalLayout.addWidget(self.sw_5_rb_s1)
        self.sw_6_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.sw_6_rb_s1.setEnabled(False)
        self.sw_6_rb_s1.setAutoExclusive(False)
        self.sw_6_rb_s1.setObjectName("sw_6_rb_s1")
        self.verticalLayout.addWidget(self.sw_6_rb_s1)
        self.sw_7_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.sw_7_rb_s1.setEnabled(False)
        self.sw_7_rb_s1.setAutoExclusive(False)
        self.sw_7_rb_s1.setObjectName("sw_7_rb_s1")
        self.verticalLayout.addWidget(self.sw_7_rb_s1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(190, 30, 180, 227))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sw_8_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.sw_8_rb_s1.setEnabled(False)
        self.sw_8_rb_s1.setAutoExclusive(False)
        self.sw_8_rb_s1.setObjectName("sw_8_rb_s1")
        self.verticalLayout_2.addWidget(self.sw_8_rb_s1)
        self.sw_9_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.sw_9_rb_s1.setEnabled(False)
        self.sw_9_rb_s1.setAutoExclusive(False)
        self.sw_9_rb_s1.setObjectName("sw_9_rb_s1")
        self.verticalLayout_2.addWidget(self.sw_9_rb_s1)
        self.sw_10_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.sw_10_rb_s1.setEnabled(False)
        self.sw_10_rb_s1.setAutoExclusive(False)
        self.sw_10_rb_s1.setObjectName("sw_10_rb_s1")
        self.verticalLayout_2.addWidget(self.sw_10_rb_s1)
        self.sw_11_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.sw_11_rb_s1.setEnabled(False)
        self.sw_11_rb_s1.setAutoExclusive(False)
        self.sw_11_rb_s1.setObjectName("sw_11_rb_s1")
        self.verticalLayout_2.addWidget(self.sw_11_rb_s1)
        self.sw_12_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.sw_12_rb_s1.setEnabled(False)
        self.sw_12_rb_s1.setAutoExclusive(False)
        self.sw_12_rb_s1.setObjectName("sw_12_rb_s1")
        self.verticalLayout_2.addWidget(self.sw_12_rb_s1)
        self.sw_13_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.sw_13_rb_s1.setEnabled(False)
        self.sw_13_rb_s1.setAutoExclusive(False)
        self.sw_13_rb_s1.setObjectName("sw_13_rb_s1")
        self.verticalLayout_2.addWidget(self.sw_13_rb_s1)
        self.sw_14_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.sw_14_rb_s1.setEnabled(False)
        self.sw_14_rb_s1.setAutoExclusive(False)
        self.sw_14_rb_s1.setObjectName("sw_14_rb_s1")
        self.verticalLayout_2.addWidget(self.sw_14_rb_s1)
        self.sw_15_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.sw_15_rb_s1.setEnabled(False)
        self.sw_15_rb_s1.setAutoExclusive(False)
        self.sw_15_rb_s1.setObjectName("sw_15_rb_s1")
        self.verticalLayout_2.addWidget(self.sw_15_rb_s1)
        self.statusword_bin_lb_s1 = QtWidgets.QLabel(self.groupBox)
        self.statusword_bin_lb_s1.setGeometry(QtCore.QRect(10, 270, 261, 24))
        self.statusword_bin_lb_s1.setFrameShape(QtWidgets.QFrame.Box)
        self.statusword_bin_lb_s1.setObjectName("statusword_bin_lb_s1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 320, 381, 321))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_3.setEnabled(True)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 171, 256))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.digin_0_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.digin_0_rb_s1.setEnabled(False)
        self.digin_0_rb_s1.setAutoExclusive(False)
        self.digin_0_rb_s1.setObjectName("digin_0_rb_s1")
        self.verticalLayout_3.addWidget(self.digin_0_rb_s1)
        self.digin_1_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.digin_1_rb_s1.setEnabled(False)
        self.digin_1_rb_s1.setAutoExclusive(False)
        self.digin_1_rb_s1.setObjectName("digin_1_rb_s1")
        self.verticalLayout_3.addWidget(self.digin_1_rb_s1)
        self.digin_2_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.digin_2_rb_s1.setEnabled(False)
        self.digin_2_rb_s1.setAutoExclusive(False)
        self.digin_2_rb_s1.setObjectName("digin_2_rb_s1")
        self.verticalLayout_3.addWidget(self.digin_2_rb_s1)
        self.digin_16_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.digin_16_rb_s1.setEnabled(False)
        self.digin_16_rb_s1.setAutoExclusive(False)
        self.digin_16_rb_s1.setObjectName("digin_16_rb_s1")
        self.verticalLayout_3.addWidget(self.digin_16_rb_s1)
        self.digin_17_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.digin_17_rb_s1.setEnabled(False)
        self.digin_17_rb_s1.setAutoExclusive(False)
        self.digin_17_rb_s1.setObjectName("digin_17_rb_s1")
        self.verticalLayout_3.addWidget(self.digin_17_rb_s1)
        self.digin_18_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.digin_18_rb_s1.setEnabled(False)
        self.digin_18_rb_s1.setAutoExclusive(False)
        self.digin_18_rb_s1.setObjectName("digin_18_rb_s1")
        self.verticalLayout_3.addWidget(self.digin_18_rb_s1)
        self.digin_20_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.digin_20_rb_s1.setEnabled(False)
        self.digin_20_rb_s1.setAutoExclusive(False)
        self.digin_20_rb_s1.setObjectName("digin_20_rb_s1")
        self.verticalLayout_3.addWidget(self.digin_20_rb_s1)
        self.digin_21_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.digin_21_rb_s1.setEnabled(False)
        self.digin_21_rb_s1.setAutoExclusive(False)
        self.digin_21_rb_s1.setObjectName("digin_21_rb_s1")
        self.verticalLayout_3.addWidget(self.digin_21_rb_s1)
        self.digin_22_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.digin_22_rb_s1.setEnabled(False)
        self.digin_22_rb_s1.setAutoExclusive(False)
        self.digin_22_rb_s1.setObjectName("digin_22_rb_s1")
        self.verticalLayout_3.addWidget(self.digin_22_rb_s1)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(190, 30, 180, 256))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.digin_23_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.digin_23_rb_s1.setEnabled(False)
        self.digin_23_rb_s1.setAutoExclusive(False)
        self.digin_23_rb_s1.setObjectName("digin_23_rb_s1")
        self.verticalLayout_4.addWidget(self.digin_23_rb_s1)
        self.digin_24_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.digin_24_rb_s1.setEnabled(False)
        self.digin_24_rb_s1.setAutoExclusive(False)
        self.digin_24_rb_s1.setObjectName("digin_24_rb_s1")
        self.verticalLayout_4.addWidget(self.digin_24_rb_s1)
        self.digin_25_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.digin_25_rb_s1.setEnabled(False)
        self.digin_25_rb_s1.setAutoExclusive(False)
        self.digin_25_rb_s1.setObjectName("digin_25_rb_s1")
        self.verticalLayout_4.addWidget(self.digin_25_rb_s1)
        self.digin_26_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.digin_26_rb_s1.setEnabled(False)
        self.digin_26_rb_s1.setAutoExclusive(False)
        self.digin_26_rb_s1.setObjectName("digin_26_rb_s1")
        self.verticalLayout_4.addWidget(self.digin_26_rb_s1)
        self.digin_27_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.digin_27_rb_s1.setEnabled(False)
        self.digin_27_rb_s1.setAutoExclusive(False)
        self.digin_27_rb_s1.setObjectName("digin_27_rb_s1")
        self.verticalLayout_4.addWidget(self.digin_27_rb_s1)
        self.digin_28_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.digin_28_rb_s1.setEnabled(False)
        self.digin_28_rb_s1.setAutoExclusive(False)
        self.digin_28_rb_s1.setObjectName("digin_28_rb_s1")
        self.verticalLayout_4.addWidget(self.digin_28_rb_s1)
        self.digin_29_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.digin_29_rb_s1.setEnabled(False)
        self.digin_29_rb_s1.setAutoExclusive(False)
        self.digin_29_rb_s1.setObjectName("digin_29_rb_s1")
        self.verticalLayout_4.addWidget(self.digin_29_rb_s1)
        self.digin_30_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.digin_30_rb_s1.setEnabled(False)
        self.digin_30_rb_s1.setAutoExclusive(False)
        self.digin_30_rb_s1.setObjectName("digin_30_rb_s1")
        self.verticalLayout_4.addWidget(self.digin_30_rb_s1)
        self.digin_31_rb_s1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.digin_31_rb_s1.setEnabled(False)
        self.digin_31_rb_s1.setAutoExclusive(False)
        self.digin_31_rb_s1.setObjectName("digin_31_rb_s1")
        self.verticalLayout_4.addWidget(self.digin_31_rb_s1)
        self.digitalinputs_lb_s1 = QtWidgets.QLabel(self.groupBox_2)
        self.digitalinputs_lb_s1.setGeometry(QtCore.QRect(10, 290, 261, 24))
        self.digitalinputs_lb_s1.setFrameShape(QtWidgets.QFrame.Box)
        self.digitalinputs_lb_s1.setObjectName("digitalinputs_lb_s1")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(250, 460, 131, 161))
        self.groupBox_4.setObjectName("groupBox_4")
        self.connect_pb_s1 = QtWidgets.QPushButton(self.groupBox_4)
        self.connect_pb_s1.setGeometry(QtCore.QRect(10, 60, 111, 51))
        self.connect_pb_s1.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.connect_pb_s1.setCheckable(True)
        self.connect_pb_s1.setChecked(False)
        self.connect_pb_s1.setObjectName("connect_pb_s1")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 460, 221, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 201, 125))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.mode_status_cb_s1 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.mode_status_cb_s1.setEnabled(False)
        self.mode_status_cb_s1.setObjectName("mode_status_cb_s1")
        self.mode_status_cb_s1.addItem("")
        self.mode_status_cb_s1.addItem("")
        self.mode_status_cb_s1.addItem("")
        self.mode_status_cb_s1.addItem("")
        self.mode_status_cb_s1.addItem("")
        self.mode_status_cb_s1.addItem("")
        self.mode_status_cb_s1.addItem("")
        self.mode_status_cb_s1.addItem("")
        self.mode_status_cb_s1.addItem("")
        self.mode_status_cb_s1.addItem("")
        self.mode_status_cb_s1.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mode_status_cb_s1)
        self.act_vel_le_s1 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.act_vel_le_s1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.act_vel_le_s1.sizePolicy().hasHeightForWidth())
        self.act_vel_le_s1.setSizePolicy(sizePolicy)
        self.act_vel_le_s1.setMaxLength(16)
        self.act_vel_le_s1.setObjectName("act_vel_le_s1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.act_vel_le_s1)
        self.act_pos_le_s1 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.act_pos_le_s1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.act_pos_le_s1.sizePolicy().hasHeightForWidth())
        self.act_pos_le_s1.setSizePolicy(sizePolicy)
        self.act_pos_le_s1.setMaxLength(16)
        self.act_pos_le_s1.setObjectName("act_pos_le_s1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.act_pos_le_s1)
        self.act_trq_le_s1 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.act_trq_le_s1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.act_trq_le_s1.sizePolicy().hasHeightForWidth())
        self.act_trq_le_s1.setSizePolicy(sizePolicy)
        self.act_trq_le_s1.setMaxLength(16)
        self.act_trq_le_s1.setObjectName("act_trq_le_s1")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.act_trq_le_s1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 231, 111))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox.setMaximum(999)
        self.spinBox.setProperty("value", 502)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 2, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_25.setEnabled(True)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 2, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(140, 140, 93, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 140, 121, 30))
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 180, 311, 191))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 25))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionAbout)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Main Control "))
        self.label_11.setText(_translate("MainWindow", "Distance"))
        self.label_9.setText(_translate("MainWindow", "Direction (F/B)"))
        self.start_pb_s1.setText(_translate("MainWindow", "ON"))
        self.label_20.setText(_translate("MainWindow", "Error_ID"))
        self.label_2.setText(_translate("MainWindow", "ACC"))
        self.modeSelection_cb_s1.setItemText(0, _translate("MainWindow", "Jog Mode"))
        self.modeSelection_cb_s1.setItemText(1, _translate("MainWindow", "Absolute Move"))
        self.modeSelection_cb_s1.setItemText(2, _translate("MainWindow", "Relative Move"))
        self.modeSelection_cb_s1.setItemText(3, _translate("MainWindow", "Velocity Mode"))
        self.modeSelection_cb_s1.setItemText(4, _translate("MainWindow", "Sync Absolute Mode"))
        self.modeSelection_cb_s1.setItemText(5, _translate("MainWindow", "Sync Veloctiy Mode"))
        self.label_4.setText(_translate("MainWindow", "Servo Power"))
        self.servoOn_pb_s1.setText(_translate("MainWindow", "ON"))
        self.label_10.setText(_translate("MainWindow", "Position"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Servo1 - Control Page</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Mode Selection"))
        self.label_3.setText(_translate("MainWindow", "Velocity"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Status </span></p></body></html>"))
        self.mcerror_cb_s1.setItemText(0, _translate("MainWindow", "No MC Error"))
        self.mcerror_cb_s1.setItemText(1, _translate("MainWindow", "MC Power Error"))
        self.mcerror_cb_s1.setItemText(2, _translate("MainWindow", "MC Reset  Error"))
        self.mcerror_cb_s1.setItemText(3, _translate("MainWindow", "MC MoveError"))
        self.mcerror_cb_s1.setItemText(4, _translate("MainWindow", "MC Jog  Error"))
        self.mcerror_cb_s1.setItemText(5, _translate("MainWindow", "MC Velecity Error"))
        self.mcerror_cb_s1.setItemText(6, _translate("MainWindow", "MC Sync Absolute Error"))
        self.mcerror_cb_s1.setItemText(7, _translate("MainWindow", "MC Sync Velocity Error"))
        self.label_8.setText(_translate("MainWindow", "DEC"))
        self.errID_lb_s1.setText(_translate("MainWindow", "MC Error"))
        self.dir_lb_s1.setText(_translate("MainWindow", "dir_Status"))
        self.label.setText(_translate("MainWindow", "Servo Execute"))
        self.reset_pb_s1.setText(_translate("MainWindow", "RESET"))
        self.driver_error_lb_s1.setText(_translate("MainWindow", "Driver Error"))
        self.statusword_lb_s1.setText(_translate("MainWindow", "statusword"))
        self.groupBox.setTitle(_translate("MainWindow", "Status Word"))
        self.sw_0_rb_s1.setText(_translate("MainWindow", "0: Ready Switch ON"))
        self.sw_1_rb_s1.setText(_translate("MainWindow", "1: Switched On"))
        self.sw_2_rb_s1.setText(_translate("MainWindow", "2: Operation Enabled"))
        self.sw_3_rb_s1.setText(_translate("MainWindow", "3: Fault"))
        self.sw_4_rb_s1.setText(_translate("MainWindow", "4: Voltage Enabled"))
        self.sw_5_rb_s1.setText(_translate("MainWindow", "5: Quick Stop"))
        self.sw_6_rb_s1.setText(_translate("MainWindow", "6: Switch On disabled"))
        self.sw_7_rb_s1.setText(_translate("MainWindow", "7: Warning"))
        self.sw_8_rb_s1.setText(_translate("MainWindow", "8: Reserved"))
        self.sw_9_rb_s1.setText(_translate("MainWindow", "9: Remote"))
        self.sw_10_rb_s1.setText(_translate("MainWindow", "10: Operation Mode spec"))
        self.sw_11_rb_s1.setText(_translate("MainWindow", "11: Internal limit actv."))
        self.sw_12_rb_s1.setText(_translate("MainWindow", "12: Operation Mode spec"))
        self.sw_13_rb_s1.setText(_translate("MainWindow", "13: Operation Mode spec"))
        self.sw_14_rb_s1.setText(_translate("MainWindow", "14: Reserved"))
        self.sw_15_rb_s1.setText(_translate("MainWindow", "15: Reserved"))
        self.statusword_bin_lb_s1.setText(_translate("MainWindow", "statusword binary"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Digital Inputs"))
        self.digin_0_rb_s1.setText(_translate("MainWindow", "0: NOT"))
        self.digin_1_rb_s1.setText(_translate("MainWindow", "1: POT"))
        self.digin_2_rb_s1.setText(_translate("MainWindow", "2: DEC"))
        self.digin_16_rb_s1.setText(_translate("MainWindow", "16: PC"))
        self.digin_17_rb_s1.setText(_translate("MainWindow", "17: EXT1"))
        self.digin_18_rb_s1.setText(_translate("MainWindow", "18: EXT2"))
        self.digin_20_rb_s1.setText(_translate("MainWindow", "20: MON1"))
        self.digin_21_rb_s1.setText(_translate("MainWindow", "21: MON2"))
        self.digin_22_rb_s1.setText(_translate("MainWindow", "22: MON3"))
        self.digin_23_rb_s1.setText(_translate("MainWindow", "23: PCL"))
        self.digin_24_rb_s1.setText(_translate("MainWindow", "24: NCL"))
        self.digin_25_rb_s1.setText(_translate("MainWindow", "25: ESTP"))
        self.digin_26_rb_s1.setText(_translate("MainWindow", "26: Breake Lock"))
        self.digin_27_rb_s1.setText(_translate("MainWindow", "27: STO1"))
        self.digin_28_rb_s1.setText(_translate("MainWindow", "28: STO2"))
        self.digin_29_rb_s1.setText(_translate("MainWindow", "29: EDM OUTPUT"))
        self.digin_30_rb_s1.setText(_translate("MainWindow", "30: MON4"))
        self.digin_31_rb_s1.setText(_translate("MainWindow", "31: MON5"))
        self.digitalinputs_lb_s1.setText(_translate("MainWindow", "digital inputs"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Control"))
        self.connect_pb_s1.setText(_translate("MainWindow", "CONNECT"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Actual Values"))
        self.label_12.setText(_translate("MainWindow", "Mode"))
        self.label_15.setText(_translate("MainWindow", "Vel"))
        self.label_13.setText(_translate("MainWindow", "Pos"))
        self.label_14.setText(_translate("MainWindow", "Torque"))
        self.mode_status_cb_s1.setItemText(0, _translate("MainWindow", "Mode not Selected"))
        self.mode_status_cb_s1.setItemText(1, _translate("MainWindow", "Profile Position Mode"))
        self.mode_status_cb_s1.setItemText(2, _translate("MainWindow", "reserved"))
        self.mode_status_cb_s1.setItemText(3, _translate("MainWindow", "Profile Velocity Mode"))
        self.mode_status_cb_s1.setItemText(4, _translate("MainWindow", "reserved"))
        self.mode_status_cb_s1.setItemText(5, _translate("MainWindow", "reserved"))
        self.mode_status_cb_s1.setItemText(6, _translate("MainWindow", "Homming Mode"))
        self.mode_status_cb_s1.setItemText(7, _translate("MainWindow", "reserved"))
        self.mode_status_cb_s1.setItemText(8, _translate("MainWindow", "Cyclic Position Mode"))
        self.mode_status_cb_s1.setItemText(9, _translate("MainWindow", "Cyclic Velocity Mode"))
        self.mode_status_cb_s1.setItemText(10, _translate("MainWindow", "Cyclic Torque Mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Servo 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Servo 2"))
        self.label_21.setText(_translate("MainWindow", "PLC IP Adress"))
        self.lineEdit_3.setText(_translate("MainWindow", "192.168.0.131"))
        self.label_22.setText(_translate("MainWindow", "Port Number"))
        self.label_24.setText(_translate("MainWindow", "Error"))
        self.label_25.setText(_translate("MainWindow", "Error ID"))
        self.pushButton_4.setText(_translate("MainWindow", "Connect"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "CLOSED"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "LISTEN"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "SYN SENT"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "SYN RECIEVED"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "ESTABLISHED"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "CLOSE WAIT"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "FIN WAIT 1"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "CLOSING"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "LAST ACK"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "FIN WAIT 2"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "TIME WAIT"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "0001ILLEGAL FUNCTION\n"
"0002 ILLEGAL DATA ADDRESS\n"
"0003 ILLEGAL DATA VALUE\n"
"2000 Local IP Address Setting Error\n"
"2001 TCP/UDP Port Already in Use\n"
"2002 Address Resolution Failed\n"
"2003 Status Error\n"
"2004 Local IP Address Not Set\n"
"2006 Socket Timeout\n"
"2007 Socket Handle Out of Range\n"
"2008 Socket Communications Resource Overflow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Communication"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
